language: cpp
compiler:
  - gcc
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-5']
    env: SCRIPT=cmake CMAKE_CXX_COMPILER=g++-5
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - ../etlTest


